// <auto-generated />
namespace StoreManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SaleDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SaleDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201811131119371_SaleDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
